services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./static:/root/static
      - ./templates:/root/templates
    depends_on:
      - db

  db:
    image: keinos/sqlite3:latest
    container_name: sqlite
    volumes:
      - sqlite_data:/data
    command: ["sqlite3", "/data/blog.db"]

volumes:
  sqlite_data:
